const $ = (id) => document.getElementById(id);

const state = {
  org: "",
  owners: [],
  members: [],
  links: []
};

function setStatus(msg, isError=false){
  const el = $("status");
  el.textContent = msg;
  el.className = "status" + (isError ? " error" : "");
}

function renderPeople(containerId, people){
  const el = $(containerId);
  el.innerHTML = "";
  if (!people.length){
    el.innerHTML = `<p class="muted small">No data yet.</p>`;
    return;
  }
  for (const p of people){
    const card = document.createElement("div");
    card.className = "person";
    card.innerHTML = `
      <img class="avatar" src="${p.avatar_url}" alt="${p.login}" />
      <div class="meta">
        <div class="name" title="${p.login}">${p.login}</div>
        <div class="sub"><a href="${p.html_url}" target="_blank" rel="noreferrer">View profile</a></div>
      </div>
    `;
    el.appendChild(card);
  }
}

function renderLinks(){
  const el = $("linksList");
  el.innerHTML = "";
  for (let i=0;i<state.links.length;i++){
    const link = state.links[i];
    const chip = document.createElement("div");
    chip.className = "chip";
    chip.innerHTML = `
      <span><strong>${escapeHtml(link.label)}</strong>: <a href="${escapeAttr(link.url)}" target="_blank" rel="noreferrer">${escapeHtml(link.url)}</a></span>
      <button title="Remove" aria-label="Remove">×</button>
    `;
    chip.querySelector("button").addEventListener("click", () => {
      state.links.splice(i, 1);
      renderLinks();
    });
    el.appendChild(chip);
  }
}

function escapeHtml(s){
  return String(s)
    .replaceAll("&","&amp;")
    .replaceAll("<","&lt;")
    .replaceAll(">","&gt;")
    .replaceAll('"',"&quot;")
    .replaceAll("'","&#039;");
}
function escapeAttr(s){ return escapeHtml(s); }

async function ghJson(url){
  const res = await fetch(url, {
    headers: {
      "Accept": "application/vnd.github+json"
    }
  });
  if (!res.ok){
    const text = await res.text().catch(()=> "");
    throw new Error(`GitHub API error ${res.status}: ${text || res.statusText}`);
  }
  return res.json();
}

async function loadOrg(org){
  state.org = org;
  state.owners = [];
  state.members = [];
  renderPeople("ownersGrid", []);
  renderPeople("membersGrid", []);
  setStatus("Loading…");

  // 1) Get org (basic validation)
  await ghJson(`https://api.github.com/orgs/${encodeURIComponent(org)}`);

  // 2) Fetch members with role=admin (owners-ish) and role=member.
  // NOTE: This endpoint returns public members for unauthenticated requests.
  const [admins, members] = await Promise.all([
    ghJson(`https://api.github.com/orgs/${encodeURIComponent(org)}/members?per_page=100&role=admin`),
    ghJson(`https://api.github.com/orgs/${encodeURIComponent(org)}/members?per_page=100&role=member`)
  ]);

  state.owners = admins || [];
  state.members = members || [];

  renderPeople("ownersGrid", state.owners);
  renderPeople("membersGrid", state.members);

  setStatus(`Loaded: ${state.owners.length} owner/admin, ${state.members.length} members (public).`);
}

function buildReadmeMarkdown(){
  const lines = [];
  lines.push(`# ${state.org} team`);
  lines.push("");
  if (state.links.length){
    lines.push("## Links");
    for (const l of state.links){
      lines.push(`- **${l.label}**: ${l.url}`);
    }
    lines.push("");
  }

  const owners = state.owners.map(p => `- [@${p.login}](${p.html_url})`).join("\n");
  const members = state.members.map(p => `- [@${p.login}](${p.html_url})`).join("\n");

  lines.push("## Founder / Owners");
  lines.push(owners || "_None found (public)._");
  lines.push("");
  lines.push("## Members");
  lines.push(members || "_None found (public)._");
  lines.push("");

  lines.push("> Generated by organization-team-site");
  return lines.join("\n");
}

function buildHtmlEmbed(){
  const links = state.links.map(l =>
    `<li><strong>${escapeHtml(l.label)}</strong>: <a href="${escapeAttr(l.url)}" target="_blank" rel="noreferrer">${escapeHtml(l.url)}</a></li>`
  ).join("");

  const owners = state.owners.map(p => `
    <div class="person">
      <img class="avatar" src="${escapeAttr(p.avatar_url)}" alt="${escapeAttr(p.login)}" />
      <div class="meta">
        <div class="name">${escapeHtml(p.login)}</div>
        <div class="sub"><a href="${escapeAttr(p.html_url)}" target="_blank" rel="noreferrer">View profile</a></div>
      </div>
    </div>
  `).join("");

  const members = state.members.map(p => `
    <div class="person">
      <img class="avatar" src="${escapeAttr(p.avatar_url)}" alt="${escapeAttr(p.login)}" />
      <div class="meta">
        <div class="name">${escapeHtml(p.login)}</div>
        <div class="sub"><a href="${escapeAttr(p.html_url)}" target="_blank" rel="noreferrer">View profile</a></div>
      </div>
    </div>
  `).join("");

  return `<!-- Organization Team Embed: ${escapeHtml(state.org)} -->
<div class="org-team-embed">
  <h2>${escapeHtml(state.org)} team</h2>

  ${state.links.length ? `<h3>Links</h3><ul>${links}</ul>` : ""}

  <h3>Founder / Owners</h3>
  <div class="people">${owners || "<p><em>None found (public).</em></p>"}</div>

  <h3>Members</h3>
  <div class="people">${members || "<p><em>None found (public).</em></p>"}</div>
</div>`;
}

function enableCopyIfOutput(){
  $("copyBtn").disabled = !$("output").value.trim();
}

$("loadBtn").addEventListener("click", async () => {
  const org = $("orgInput").value.trim();
  if (!org) return setStatus("Please enter an organization name.", true);
  try{
    await loadOrg(org);
  }catch(e){
    console.error(e);
    setStatus(e.message || "Failed to load org.", true);
  }
});

$("addLinkBtn").addEventListener("click", () => {
  const label = $("linkLabel").value.trim() || "Link";
  const url = $("linkUrl").value.trim();
  if (!url) return setStatus("Please enter a URL to add.", true);
  state.links.push({label, url});
  $("linkLabel").value = "";
  $("linkUrl").value = "";
  renderLinks();
  setStatus("Link added.");
});

$("genReadmeBtn").addEventListener("click", () => {
  if (!state.org) return setStatus("Load an org first.", true);
  $("output").value = buildReadmeMarkdown();
  enableCopyIfOutput();
  setStatus("Markdown generated.");
});

$("genHtmlBtn").addEventListener("click", () => {
  if (!state.org) return setStatus("Load an org first.", true);
  $("output").value = buildHtmlEmbed();
  enableCopyIfOutput();
  setStatus("HTML embed generated.");
});

$("copyBtn").addEventListener("click", async () => {
  const text = $("output").value;
  if (!text.trim()) return;
  await navigator.clipboard.writeText(text);
  setStatus("Copied to clipboard.");
});

$("output").addEventListener("input", enableCopyIfOutput);

renderLinks();
renderPeople("ownersGrid", []);
renderPeople("membersGrid", []);
setStatus("Ready.");
