const $ = (id) => document.getElementById(id);

const state = {
  org: "",
  owners: [],
  members: [],
  links: []
};

// IMPORTANT:
// GitHub Pages is static, so `/api/card.svg` does NOT exist on the Pages domain.
// Set this to your deployed card-service base URL (Cloudflare Worker) once deployed.
// Example: https://org-team-card.<you>.workers.dev
const CARD_SERVICE_BASE_URL = "";

function setStatus(msg, isError=false){
  const el = $("status");
  el.textContent = msg;
  el.className = "status" + (isError ? " error" : "");
}

function renderPeople(containerId, people){
  const el = $(containerId);
  el.innerHTML = "";
  if (!people.length){
    el.innerHTML = `<p class="muted small">No data yet.</p>`;
    return;
  }
  for (const p of people){
    const card = document.createElement("div");
    card.className = "person";
    card.innerHTML = `
      <img class="avatar" src="${p.avatar_url}" alt="${p.login}" />
      <div class="meta">
        <div class="name" title="${p.login}">${p.login}</div>
        <div class="sub"><a href="${p.html_url}" target="_blank" rel="noreferrer">View profile</a></div>
      </div>
    `;
    el.appendChild(card);
  }
}

function renderLinks(){
  const el = $("linksList");
  el.innerHTML = "";
  for (let i=0;i<state.links.length;i++){
    const link = state.links[i];
    const chip = document.createElement("div");
    chip.className = "chip";
    chip.innerHTML = `
      <span><strong>${escapeHtml(link.label)}</strong>: <a href="${escapeAttr(link.url)}" target="_blank" rel="noreferrer">${escapeHtml(link.url)}</a></span>
      <button title="Remove" aria-label="Remove">×</button>
    `;
    chip.querySelector("button").addEventListener("click", () => {
      state.links.splice(i, 1);
      renderLinks();
    });
    el.appendChild(chip);
  }
}

function escapeHtml(s){
  return String(s)
    .replaceAll("&","&amp;")
    .replaceAll("<","&lt;")
    .replaceAll(">","&gt;")
    .replaceAll('"',"&quot;")
    .replaceAll("'","&#039;");
}
function escapeAttr(s){ return escapeHtml(s); }

async function ghJson(url){
  const res = await fetch(url, {
    headers: {
      "Accept": "application/vnd.github+json"
    }
  });
  if (!res.ok){
    const text = await res.text().catch(()=> "");
    throw new Error(`GitHub API error ${res.status}: ${text || res.statusText}`);
  }
  return res.json();
}

async function loadOrg(org){
  state.org = org;
  state.owners = [];
  state.members = [];
  renderPeople("ownersGrid", []);
  renderPeople("membersGrid", []);
  setStatus("Loading…");

  await ghJson(`https://api.github.com/orgs/${encodeURIComponent(org)}`);

  const [admins, members] = await Promise.all([
    ghJson(`https://api.github.com/orgs/${encodeURIComponent(org)}/members?per_page=100&role=admin`),
    ghJson(`https://api.github.com/orgs/${encodeURIComponent(org)}/members?per_page=100&role=member`)
  ]);

  state.owners = admins || [];
  state.members = members || [];

  renderPeople("ownersGrid", state.owners);
  renderPeople("membersGrid", state.members);

  setStatus(`Loaded: ${state.owners.length} owner/admin, ${state.members.length} members (public).`);
}

function cardUrlForOrg(org){
  const qs = `org=${encodeURIComponent(org)}`;

  // If you deployed the worker, this becomes a working full URL.
  if (CARD_SERVICE_BASE_URL && CARD_SERVICE_BASE_URL.startsWith("http")){
    return `${CARD_SERVICE_BASE_URL.replace(/\/$/, "")}/api/card.svg?${qs}`;
  }

  // Fallback: explain why it doesn't work on GitHub Pages
  // (still returns a value so user can see what endpoint would be)
  return `/api/card.svg?${qs}`;
}

function buildReadmeMarkdown(){
  const lines = [];
  lines.push(`# ${state.org} team`);
  lines.push("");

  lines.push("## Team card");
  lines.push("");
  lines.push(`![${state.org} team card](${cardUrlForOrg(state.org)})`);
  lines.push("");

  if (!CARD_SERVICE_BASE_URL){
    lines.push("> Note: Set `CARD_SERVICE_BASE_URL` in `app.js` after deploying the card-service (Cloudflare Worker), otherwise the image URL won’t work on GitHub Pages.");
    lines.push("");
  }

  if (state.links.length){
    lines.push("## Links");
    for (const l of state.links){
      lines.push(`- **${l.label}**: ${l.url}`);
    }
    lines.push("");
  }

  const owners = state.owners.map(p => `- [@${p.login}](${p.html_url})`).join("\n");
  const members = state.members.map(p => `- [@${p.login}](${p.html_url})`).join("\n");

  lines.push("## Founder / Owners");
  lines.push(owners || "_None found (public)._" );
  lines.push("");
  lines.push("## Members");
  lines.push(members || "_None found (public)._" );
  lines.push("");

  lines.push("> Generated by organization-team-site");
  return lines.join("\n");
}

function buildHtmlEmbed(){
  const url = cardUrlForOrg(state.org);
  return `<!-- Org team card embed -->\n<img alt="${escapeAttr(state.org)} team card" src="${url}" />`;
}

function buildCardUrl(){
  return cardUrlForOrg(state.org);
}

function enableCopyIfOutput(){
  $("copyBtn").disabled = !$("output").value.trim();
}

$("loadBtn").addEventListener("click", async () => {
  const org = $("orgInput").value.trim();
  if (!org) return setStatus("Please enter an organization name.", true);
  try{
    await loadOrg(org);
  }catch(e){
    console.error(e);
    setStatus(e.message || "Failed to load org.", true);
  }
});

$("addLinkBtn").addEventListener("click", () => {
  const label = $("linkLabel").value.trim() || "Link";
  const url = $("linkUrl").value.trim();
  if (!url) return setStatus("Please enter a URL to add.", true);
  state.links.push({label, url});
  $("linkLabel").value = "";
  $("linkUrl").value = "";
  renderLinks();
  setStatus("Link added.");
});

$("genReadmeBtn").addEventListener("click", () => {
  if (!state.org) return setStatus("Load an org first.", true);
  $("output").value = buildReadmeMarkdown();
  enableCopyIfOutput();
  setStatus("Markdown generated.");
});

$("genHtmlBtn").addEventListener("click", () => {
  if (!state.org) return setStatus("Load an org first.", true);
  $("output").value = buildHtmlEmbed();
  enableCopyIfOutput();
  setStatus("HTML embed generated.");
});

$("genCardUrlBtn").addEventListener("click", () => {
  if (!state.org) return setStatus("Load an org first.", true);
  $("output").value = buildCardUrl();
  enableCopyIfOutput();

  if (!CARD_SERVICE_BASE_URL){
    setStatus("Card URL generated, but won’t work on GitHub Pages until you deploy card-service and set CARD_SERVICE_BASE_URL.", true);
  } else {
    setStatus("Card URL generated.");
  }
});

$("copyBtn").addEventListener("click", async () => {
  const text = $("output").value;
  if (!text.trim()) return;
  await navigator.clipboard.writeText(text);
  setStatus("Copied to clipboard.");
});

$("output").addEventListener("input", enableCopyIfOutput);

renderLinks();
renderPeople("ownersGrid", []);
renderPeople("membersGrid", []);
setStatus("Ready.");
